api_version = "2024-07"

[[extensions]]
name = "Bundle $29 Discount"
handle = "bundle-discount"
type = "function"

[[extensions.targeting]]
target = "purchase.product-discount.run"
input_query = "input.graphql"
export = "run"

[extensions.build]
command = ""
path = "dist/function.wasm"
